spring:
  application:
    name: frustratedfunctordotdev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:-jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:-postgres}
    password: ${DB_PASSWORD:-postgres}

app:
  umami:
    baseUrl: ${UMAMI_BASE_URL:-http://localhost:3002}
    websiteId: ${UMAMI_WEBSITE_ID:-123456}
