spring:
  application:
    name: frustratedfunctordotdev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

app:
  umami:
    baseUrl: ${UMAMI_BASE_URL:-http://localhost:3002}
    websiteId: ${UMAMI_WEBSITE_ID:-123456}
